version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smartlibrary-db
    restart: always
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_management"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: smartlibrary-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=9a674725e228392d4734a6217436688e14674725e228392d4734a6217436688e
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: smartlibrary-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pg-data:
