# Server config
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/library_management
spring.datasource.username=postgres
spring.datasource.password=Almighty1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

# JPA & Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Multipart Upload Config (for book covers)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Error handling
server.error.path=/error
server.error.include-stacktrace=never
server.error.include-message=always

# Log levels
logging.level.org.springframework.security=INFO
logging.level.com.smartlibrary=DEBUG

# JWT Configuration
# Hex encoded 256-bit key for HMAC-SHA256
jwt.secret=9a674725e228392d4734a6217436688e14674725e228392d4734a6217436688e
# Access token expiration: 15 minutes (900,000 ms)
jwt.expiration.access=900000
# Refresh token expiration: 7 days (604,800,000 ms)
jwt.expiration.refresh=604800000


